<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <OutputType>Exe</OutputType>
        <TargetFramework>net9.0</TargetFramework>
        <RootNamespace>gm_codex</RootNamespace>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <PackAsTool>true</PackAsTool>
        
        <ToolCommandName>gmctl</ToolCommandName>
        <PackageOutputPath>./nupkg</PackageOutputPath>
        <Version>1.0.0</Version>
        <PackAsToolTargetFramework>net9.0</PackAsToolTargetFramework>
    </PropertyGroup>

    <ItemGroup>
      <PackageReference Include="Dapper" Version="2.1.66" />
      <PackageReference Include="JetBrains.Annotations" Version="2025.2.2" />
      <PackageReference Include="Microsoft.EntityFrameworkCore.Sqlite" Version="9.0.7" />
      <PackageReference Include="Microsoft.Extensions.Configuration.Json" Version="9.0.7" />
      <PackageReference Include="Spectre.Console" Version="0.50.0" />
      <PackageReference Include="Spectre.Console.Cli" Version="0.50.0" />
    </ItemGroup>

    <ItemGroup>
        <Content Update="appsettings.json">
            <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
        </Content>
    </ItemGroup>

    <ItemGroup>
      <Folder Include="Domain\" />
      <Folder Include="Infrastructure\" />
      <Folder Include="Resources\" />
      <Folder Include="Presentation\" />
    </ItemGroup>

    <ItemGroup>
      <None Update="Resources\Fonts\Delta Corps Priest 1.flf">
        <CopyToOutputDirectory>Always</CopyToOutputDirectory>
      </None>
    </ItemGroup>


</Project>
